"""Full STL pipeline: contours → hollow body → front → snap-fit → plug → validate → zip."""

from __future__ import annotations

import io
import zipfile

from engine.catalog import get_font, get_plug_profile
from engine.font_geometry import layout_text
from engine.product_geometry import ProductParams, build_body_and_front, sit_on_bed
from engine.validate import validate_or_explain


SAFE_CHARS = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789")


def safe_char_token(char: str) -> str:
    if char in SAFE_CHARS:
        return char
    return f"u{ord(char):04X}"


def project_slug(text: str) -> str:
    slug = "".join(ch if ch in SAFE_CHARS else "_" for ch in text.strip())
    slug = slug.strip("_") or "LightType"
    return slug[:48]


def build_readme(text: str, params: ProductParams, font_id: str, letter_count: int) -> str:
    font = get_font(font_id)
    profile = params.plug_profile
    return (
        "LIGHTTYPE\n"
        "\n"
        f"Project: {text}\n"
        "\n"
        f"Font: {font.name}\n"
        f"Height: {params.height_mm:g} mm\n"
        f"Depth: {params.depth_mm:g} mm\n"
        f"Wall thickness: {params.wall_mm:g} mm\n"
        f"Front thickness: {params.front_mm:g} mm\n"
        f"Letter spacing: {params.spacing_mm:g} mm\n"
        f"Plug profile: {profile.name}\n"
        f"Front mount: {params.front_mount}\n"
        "\n"
        "Parts:\n"
        f"{letter_count} letter bodies\n"
        f"{letter_count} removable fronts\n"
        "\n"
        "Each letter is a hollow body designed for LED strip lighting,\n"
        "with a removable snap-fit front and a rear mounting plug.\n"
        "\n"
        f"Plug: {profile.name} — {profile.subtitle}.\n"
        "Do not assume compatibility with a physical electrified bar\n"
        "until real mechanical dimensions are configured.\n"
        "\n"
        "Print the body with the open face up (back on the bed).\n"
        "Print the front face flat. No glue is required in the default snap-fit.\n"
        "\n"
        "Generated by LightType\n"
    )


def generate_parts(text: str, font_id: str, params: ProductParams, on_stage=None) -> list[dict]:
    if on_stage:
        on_stage("building_geometry", "Building geometry", 12)
    glyphs = layout_text(font_id, text, params.height_mm, params.spacing_mm)
    parts: list[dict] = []
    total = max(1, len(glyphs))
    for i, glyph in enumerate(glyphs):
        if on_stage:
            pct = 12 + int(70 * (i / total))
            on_stage("creating_hollow", f"Creating hollow bodies · {glyph.char}", pct)
        body, front = build_body_and_front(glyph.geometry, glyph.char, params)
        if on_stage:
            on_stage("creating_fronts", "Creating removable fronts", 12 + int(70 * ((i + 0.5) / total)))
        body = validate_or_explain(body, "letter body", glyph.char)
        front = validate_or_explain(front, "removable front", glyph.char)
        body = sit_on_bed(body)
        front = sit_on_bed(front)
        idx = glyph.index + 1
        token = safe_char_token(glyph.char)
        parts.append(
            {
                "char": glyph.char,
                "index": glyph.index,
                "body": body,
                "front": front,
                "body_name": f"{idx:02d}_{token}_body.stl",
                "front_name": f"{idx:02d}_{token}_front.stl",
            }
        )
    if on_stage:
        on_stage("adding_plugs", "Adding mounting plugs", 86)
        on_stage("validating", "Validating STL", 92)
    return parts


def write_zip_bytes(text: str, font_id: str, params: ProductParams, parts: list[dict]) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for part in parts:
            body_bytes = part["body"].export(file_type="stl")
            front_bytes = part["front"].export(file_type="stl")
            zf.writestr(part["body_name"], body_bytes)
            zf.writestr(part["front_name"], front_bytes)
        zf.writestr("README.txt", build_readme(text, params, font_id, len(parts)))
    return buffer.getvalue()


def params_from_request(data: dict) -> ProductParams:
    profile = get_plug_profile(data["plug_profile"])
    profile = profile.with_overrides(
        diameter_mm=data.get("plug_diameter_mm"),
        length_mm=data.get("plug_length_mm"),
        neck_diameter_mm=data.get("plug_neck_diameter_mm"),
        neck_length_mm=data.get("plug_neck_length_mm"),
        tolerance_mm=data.get("plug_tolerance_mm"),
        rotation=data.get("plug_rotation"),
    )
    return ProductParams(
        height_mm=float(data["height_mm"]),
        depth_mm=float(data["depth_mm"]),
        wall_mm=float(data["wall_mm"]),
        front_mm=float(data["front_mm"]),
        spacing_mm=float(data["spacing_mm"]),
        front_tolerance_mm=float(data.get("front_tolerance_mm", 0.25)),
        snap_fit_tolerance_mm=float(data.get("snap_fit_tolerance_mm", 0.25)),
        snap_fit_depth_mm=float(data.get("snap_fit_depth_mm", 1.2)),
        plug_profile=profile,
        plug_position=str(data.get("plug_position", "bottom-center")),
        front_mount=str(data.get("front_mount", "snap-fit")),
        rear_wall_mm=data.get("rear_wall_mm"),
    )
