"""Full STL pipeline: contours → hollow body → front → snap-fit → plug → validate → zip."""

from __future__ import annotations

import io
import zipfile

from engine.catalog import get_font, get_plug_profile, get_letter_style
from engine.connection_base import build_modular_accessory_meshes
from engine.errors import GeometryError
from engine.export_3mf import write_3mf_bytes
from engine.font_geometry import layout_text
from engine.hole_ops import MountingHoleSpec
from engine.product_geometry import ProductParams, build_body_and_front, sit_on_bed
from engine.shadow_cover import build_shadow_mesh
from engine.svg_geometry import layout_svg
from engine.validate import validate_or_explain
from engine.wall_profile import WallProfileParams


SAFE_CHARS = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789")


def safe_char_token(char: str) -> str:
    if char in SAFE_CHARS:
        return char
    return f"u{ord(char):04X}"


def project_slug(text: str) -> str:
    slug = "".join(ch if ch in SAFE_CHARS else "_" for ch in text.strip())
    slug = slug.strip("_") or "LightType"
    return slug[:48]


def build_readme(text: str, params: ProductParams, font_id: str, letter_count: int, accessories: list | None = None) -> str:
    font = get_font(font_id)
    style = params.letter_style
    mount = style.get("front_mount", params.front_mount)
    front_label = {
        "diffuser": "printed diffusers",
        "fixed": "integrated faces",
        "press-fit": "press-fit fronts",
        "snap-fit": "removable snap-fit fronts",
    }.get(mount, "fronts")
    accessory_lines = ""
    if accessories:
        accessory_lines = (
            "\nModular rail accessories:\n"
            + "\n".join(f"- {a['name']}" for a in accessories)
            + "\n"
        )
    base_note = ""
    if params.base_enabled:
        if params.base_mode == "modular":
            base_note = (
                "Modular base: each letter has sockets on both sides.\n"
                "Use connector.stl between letters, distance.stl for wider gaps,\n"
                "dummy_left/right.stl to plug unused rail sockets, and\n"
                "end_left/right.stl as full-height terminal modules (END-style).\n"
            )
        else:
            base_note = (
                "Snap base: letters join side-by-side with integrated male/female connectors.\n"
            )
    return (
        "LIGHTTYPE\n"
        "\n"
        f"Project: {text}\n"
        "\n"
        f"Font: {font.name}\n"
        f"Height: {params.height_mm:g} mm\n"
        f"Depth: {params.depth_mm:g} mm\n"
        f"Wall thickness: {params.wall_mm:g} mm\n"
        f"Front thickness: {params.front_mm:g} mm\n"
        f"Letter spacing: {params.spacing_mm:g} mm\n"
        f"Front mount: {mount}\n"
        f"Wall profile: {(params.wall_profile.profile_id if params.wall_profile else 'flat')}\n"
        "\n"
        "Parts:\n"
        f"{letter_count} letter bodies\n"
        f"{letter_count} {front_label}\n"
        f"{accessory_lines}"
        "\n"
        "Each letter is a hollow body designed for LED strip lighting.\n"
        f"{base_note}"
        "\n"
        f"{'A unified shadow cover is included as shadow_cover.stl.\n' if params.shadow_enabled else ''}"
        "\n"
        "Print the body with the open face up (back on the bed).\n"
        "Print the front/diffuser face flat.\n"
        "\n"
        "Generated by LightType\n"
    )


def generate_parts(
    text: str,
    font_id: str,
    params: ProductParams,
    on_stage=None,
    *,
    input_mode: str = "text",
    svg_content: str | None = None,
    letter_indices: list[int] | None = None,
) -> tuple[list[dict], object | None, list[dict]]:
    if on_stage:
        on_stage("building_geometry", "Building geometry", 12)
    if input_mode == "svg" and svg_content:
        glyphs = layout_svg(svg_content, params.height_mm, params.spacing_mm)
    else:
        glyphs = layout_text(
            font_id,
            text,
            params.height_mm,
            params.spacing_mm,
            base_params=params.connection_base,
        )
    if letter_indices is not None:
        wanted = set(letter_indices)
        glyphs = [g for g in glyphs if g.index in wanted]
        if not glyphs:
            raise GeometryError(
                "Couldn't find the selected letter.",
                suggestion="Pick a letter from the list and try again.",
            )
    parts: list[dict] = []
    total = max(1, len(glyphs))
    for i, glyph in enumerate(glyphs):
        if on_stage:
            pct = 12 + int(70 * (i / total))
            on_stage("creating_hollow", f"Creating hollow bodies · {glyph.char}", pct)
        body, front = build_body_and_front(
            glyph.geometry,
            glyph.char,
            params,
            glyph_bounds=glyph.glyph_bounds,
            letter_body_geom=glyph.cavity_source,
        )
        if on_stage:
            on_stage("creating_fronts", "Creating removable fronts", 12 + int(70 * ((i + 0.5) / total)))
        body = validate_or_explain(body, "letter body", glyph.char)
        front = validate_or_explain(front, "removable front", glyph.char)
        body = sit_on_bed(body)
        front = sit_on_bed(front)
        idx = glyph.index + 1
        token = safe_char_token(glyph.char)
        front_suffix = "diffuser" if params.letter_style.get("front_mount") == "diffuser" else "front"
        parts.append(
            {
                "char": glyph.char,
                "index": glyph.index,
                "body": body,
                "front": front,
                "body_name": f"{idx:02d}_{token}_body.stl",
                "front_name": f"{idx:02d}_{token}_{front_suffix}.stl",
            }
        )
    if on_stage:
        on_stage("adding_plugs", "Adding mounting plugs", 86)
        on_stage("validating", "Validating STL", 92)
    shadow_mesh = None
    if params.shadow_enabled:
        shadow_mesh = build_shadow_mesh(glyphs, params.shadow_cover, params.rear_wall)
        if shadow_mesh is not None:
            shadow_mesh = validate_or_explain(shadow_mesh, "shadow cover")
            shadow_mesh = sit_on_bed(shadow_mesh)

    accessories: list[dict] = []
    if params.connection_base.is_modular:
        if on_stage:
            on_stage("creating_fronts", "Creating modular connectors", 90)
        for item in build_modular_accessory_meshes(
            params.connection_base,
            params.depth_mm,
            letter_height_mm=params.height_mm,
            wall_mm=params.wall_mm,
        ):
            mesh = validate_or_explain(item["mesh"], item["label"], "")
            mesh = sit_on_bed(mesh)
            accessories.append({**item, "mesh": mesh})

    return parts, shadow_mesh, accessories


def write_zip_bytes(
    text: str,
    font_id: str,
    params: ProductParams,
    parts: list[dict],
    shadow_mesh=None,
    accessories: list[dict] | None = None,
) -> bytes:
    accessories = accessories or []
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for part in parts:
            body_bytes = part["body"].export(file_type="stl")
            front_bytes = part["front"].export(file_type="stl")
            zf.writestr(part["body_name"], body_bytes)
            zf.writestr(part["front_name"], front_bytes)
        for acc in accessories:
            zf.writestr(acc["name"], acc["mesh"].export(file_type="stl"))
        if shadow_mesh is not None:
            zf.writestr("shadow_cover.stl", shadow_mesh.export(file_type="stl"))
        zf.writestr("README.txt", build_readme(text, params, font_id, len(parts), accessories))
    return buffer.getvalue()


def write_export_bytes(
    text: str,
    font_id: str,
    params: ProductParams,
    parts: list[dict],
    shadow_mesh=None,
    accessories: list[dict] | None = None,
    export_format: str = "stl",
) -> tuple[bytes, str, list[str]]:
    """Return (file_bytes, download_name, file_list).

    export_format:
      - "stl": ZIP with individual STL files
      - "3mf": single 3MF with one piece per plate (Bambu/Orca style)
    """
    accessories = accessories or []
    files = [p["body_name"] for p in parts] + [p["front_name"] for p in parts]
    files.extend(a["name"] for a in accessories)
    if shadow_mesh is not None:
        files.append("shadow_cover.stl")

    slug = project_slug(text)
    fmt = (export_format or "stl").strip().lower()
    if fmt in ("3mf", "3m", "bambu"):
        data = write_3mf_bytes(parts, shadow_mesh, accessories)
        return data, f"{slug}.3mf", files

    data = write_zip_bytes(text, font_id, params, parts, shadow_mesh, accessories)
    return data, f"{slug}.zip", files + ["README.txt"]


def params_from_request(data: dict) -> ProductParams:
    profile = get_plug_profile(str(data.get("plug_profile") or "profile-a"))
    profile = profile.with_overrides(
        diameter_mm=data.get("plug_diameter_mm"),
        length_mm=data.get("plug_length_mm"),
        neck_diameter_mm=data.get("plug_neck_diameter_mm"),
        neck_length_mm=data.get("plug_neck_length_mm"),
        tolerance_mm=data.get("plug_tolerance_mm"),
        rotation=data.get("plug_rotation"),
    )
    style = get_letter_style(data.get("letter_style_id", "printed-diffuser"))
    holes_raw = data.get("mounting_holes") or []
    letter_indices = data.get("letter_indices")
    if letter_indices is not None:
        wanted = set(int(i) for i in letter_indices)
        holes_raw = [
            h for h in holes_raw
            if h.get("letter_index") is None or int(h["letter_index"]) in wanted
        ]
    holes = [MountingHoleSpec.from_dict(h) for h in holes_raw]
    wall_profile_id = str(data.get("wall_profile_id", "flat"))
    if style.get("front_mount") == "diffuser" and wall_profile_id == "flat":
        wall_profile_id = "shelf"
    params = ProductParams(
        height_mm=float(data["height_mm"]),
        depth_mm=float(data["depth_mm"]),
        wall_mm=float(data["wall_mm"]),
        front_mm=float(data["front_mm"]),
        spacing_mm=float(data["spacing_mm"]),
        front_tolerance_mm=float(data.get("front_tolerance_mm", 0.25)),
        snap_fit_tolerance_mm=float(data.get("snap_fit_tolerance_mm", 0.25)),
        snap_fit_depth_mm=float(data.get("snap_fit_depth_mm", 1.2)),
        plug_profile=profile,
        plug_position=str(data.get("plug_position", "bottom-center")),
        front_mount=str(style.get("front_mount", data.get("front_mount", "diffuser"))),
        rear_wall_mm=data.get("rear_wall_mm"),
        letter_style_id=str(data.get("letter_style_id", "printed-diffuser")),
        wall_profile=WallProfileParams(
            profile_id=wall_profile_id,
            frieze_count=int(data.get("frieze_count", 2)),
            frieze_advance_mm=float(data.get("frieze_advance_mm", 1.5)),
            frieze_spacing_mm=float(data.get("frieze_spacing_mm", 2.0)),
            close_45_base=bool(data.get("close_45_base", True)),
            inclination_mm=float(data.get("inclination_mm", 0)),
            max_angle_deg=float(data.get("max_angle_deg", 45)),
            shelf_ratio=float(data.get("shelf_ratio", 0.598)),
            shelf_step_mm=float(data.get("shelf_step_mm", 0.8)),
        ),
        mounting_holes=holes,
        base_enabled=bool(data.get("base_enabled", False)),
        base_height_mm=float(data.get("base_height_mm", 12.0)),
        base_connector_width_mm=float(data.get("base_connector_width_mm", 8.0)),
        base_position=str(data.get("base_position", "bottom")),
        base_connector_tolerance_mm=float(data.get("base_connector_tolerance_mm", 0.3)),
        base_mode=str(data.get("base_mode", "snap")),
        shadow_enabled=bool(data.get("shadow_enabled", False)),
        shadow_offset_mm=float(data.get("shadow_offset_mm", 3.0)),
        diffuser_shell_mm=float(data.get("diffuser_shell_mm", 0.85)),
        diffuser_tolerance_mm=float(data.get("diffuser_tolerance_mm", 0.15)),
        min_cavity_mm=float(data.get("min_cavity_mm", 0)) or 0.0,
        accent_lit=bool(data.get("accent_lit", True)),
        mounting_system_id=str(data.get("mounting_system_id", "none")),
        material_pack_id=str(data.get("material_pack_id", "petg-diffuser")),
    )
    if params.min_cavity_mm <= 0:
        from engine.product_geometry import default_min_cavity_mm

        params.min_cavity_mm = default_min_cavity_mm(params.wall_mm, params.depth_mm)
    return params
